### ISSUE TITLE
Web Extensions or Electron?

### ISSUE THREAD

**Issue by toastal** [trustcrypto/OnlyKey-Chrome-App#38]
It seems Chrome app support is going to slowly fade (and the launcher is definitely going away). Is there a plan to either moving to just Web Extensions (bonus: you get Firefox support as wel) or Electron?

**Comment by onlykey** [comment]
@toastal Right now we are leaning towards a chrome extension. We originally did a chrome app because there is a USB HID api for apps - https://developer.chrome.com/apps/hid 
I recently found this  - https://github.com/trezor/trezor-chrome-extension it appears that they are using the USB HID api for an extension so apparently this is supported. Since moving to an extension would keep most of the work we have already done on the app it looks like the best solution. Supporting firefox would be great but so far they don't have a USB HID api or native support for U2F. Do you know of anyone that would be interested in helping to port the app over?

**Comment by toastal** [comment]
Ah. I just checked Bugzilla and am now following those bugs as well. It's good to see that there's a route forward. I've not yet bought an OnlyKey, but I wanted to get a stronger feel towards the progress of the tooling. I know a lot about JS and browsers, but not really sure about my time at the moment.

**Comment by onlykey** [comment]
@toastal Yes, we have a way forward. It was really disappointing that Google discontinued apps as soon as we released OnlyKey :( But the app will still be supported until mid 2017. If you do find some time we would be glad for some help in this area.

**Comment by toastal** [comment]
Good. Well now there'll be some record of this for other people doing a web search. I'll probably pick one up in the coming weeks and I'm sure once I get it, I'll start to tinker with the open source stuff.

**Comment by gnujedi** [comment]
Any updates on this? Would a standalone Electron app be able to have HID access?

**Comment by onlykey** [comment]
@gnujedi We are looking at using NW.js instead of Electron because it directly supports it - https://nwjs.io/blog/chrome-apps-support/

Yes, it would have HID access. Planning on working on this in September.

**Comment by gnujedi** [comment]
Great! Thank you. One additional question: would it work as a standalone app similar to electron, or would it need Chromium to be downloaded by the user first?

**Comment by onlykey** [comment]
@gnujedi Standalone app. You might also find the python app helpful as it is a standalone command line app. https://github.com/trustcrypto/python-onlykey
